#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""پیام‌های خطای API را به هر پنج دیکشنری اضافه می‌کند (یک‌بارمصرف، نگه‌داشته شد
تا اگر بعداً کد خطای تازه‌ای اضافه شد، جای اضافه‌کردن مشخص باشد)."""
import io

BLOCKS = {
'fa': """
  // ── پیام‌های خطای API (کدها از src/lib/validate.ts می‌آیند)
  'api.badCredentials': 'نام کاربری یا رمز عبور اشتباه است.',
  'api.rateLimited': 'تلاش‌های ناموفق زیاد بود؛ {sec} ثانیه دیگر دوباره امتحان کنید.',
  'api.currentPasswordWrong': 'رمز فعلی اشتباه است.',
  'api.passwordTooShort': 'رمز عبور باید حداقل ۸ کاراکتر باشد.',
  'api.usernamePasswordRequired': 'نام کاربری و رمز عبور الزامی است.',
  'api.nameHostRequired': 'نام و هاست سرور الزامی است.',
  'api.authTypeInvalid': 'روش احراز هویت باید «رمز» یا «کلید» باشد.',
  'api.portRange': 'پورت باید عددی بین ۱ تا ۶۵۵۳۵ باشد.',
  'api.tunnelPortsRange': 'پورت محلی و خارجی باید عددی بین ۱ تا ۶۵۵۳۵ باشند.',
  'api.configFieldsRequired': 'نام، سرور و پورت الزامی است.',
  'api.protocolInvalid': 'این پروتکل پشتیبانی نمی‌شود.',
  'api.socksOnly': 'این کار فقط روی کانفیگ SOCKS5 ممکن است.',
  'api.proxyNotDeployed': 'پروکسی هنوز روی سرور اجرا نشده — اول «اجرا روی سرور» را بزنید.',
  'api.wgPubKeyMissing': 'کلید عمومی سرور (PubKey) برای WireGuard ثبت نشده — آن را در فرم کانفیگ وارد کنید.',
  'api.wgClientKeyMissing': 'کلید خصوصی کلاینت پیدا نشد — کانفیگ را دوباره بسازید.',
  'api.sniRequired': 'برای TLS یا REALITY، مقدار SNI یا دامنه الزامی است.',
  'api.protocolNoLink': 'پروتکل {protocol} لینک قابل استفاده تولید نمی‌کند.',
  'api.tunnelTypeNotImplemented': 'نوع «{type}» هنوز پیاده‌سازی نشده؛ فعلاً فقط تانل SSH معکوس پشتیبانی می‌شود.',
  'api.tunnelPortsRequired': 'تانل بدون پورت محلی و خارجی اجرا نمی‌شود.',
  'api.tunnelAlreadyRunning': 'این تانل از قبل در حال اجراست.',
  'api.idInvalid': 'شناسهٔ درخواست نامعتبر است.',
  'api.invalidRequest': 'درخواست نامعتبر است (شناسه یا مقدار ورودی).',
  'api.internal': 'خطای داخلی سرور — یک بار دیگر تلاش کنید.',
  'api.methodNotAllowed': 'این متد پشتیبانی نمی‌شود.',
  'api.configNotFound': 'کانفیگ پیدا نشد.',
  'api.serverNotFound': 'سرور پیدا نشد.',
  'api.tunnelNotFound': 'تانل پیدا نشد.',
  'api.userNotFound': 'کاربر پیدا نشد.',
  'api.userExists': 'این نام کاربری قبلاً ثبت شده است.',
  'api.cannotDeleteSelf': 'حساب خودتان را نمی‌توانید حذف کنید.',
  'api.serverHasDependents': 'این سرور {configs} کانفیگ و {tunnels} تانل دارد؛ اول آن‌ها را حذف کنید.',
  'api.deployFailed': 'اجرای پروکسی روی سرور ناموفق بود.',
  'api.unauthorized': 'نشست منقضی شده — دوباره وارد شوید.',
  'api.forbidden': 'شما به این بخش دسترسی ندارید.',
""",
'en': """
  // ── API error codes (raised in src/lib/validate.ts)
  'api.badCredentials': 'Wrong username or password.',
  'api.rateLimited': 'Too many failed attempts — try again in {sec} seconds.',
  'api.currentPasswordWrong': 'The current password is wrong.',
  'api.passwordTooShort': 'Password must be at least 8 characters.',
  'api.usernamePasswordRequired': 'Username and password are required.',
  'api.nameHostRequired': 'A server name and host are required.',
  'api.authTypeInvalid': 'Auth type must be password or key.',
  'api.portRange': 'Port must be a number between 1 and 65535.',
  'api.tunnelPortsRange': 'Local and remote ports must be numbers between 1 and 65535.',
  'api.configFieldsRequired': 'Name, server and port are required.',
  'api.protocolInvalid': 'That protocol is not supported.',
  'api.socksOnly': 'This only works on a SOCKS5 config.',
  'api.proxyNotDeployed': 'The proxy is not running on the server yet — hit "Deploy to server" first.',
  'api.wgPubKeyMissing': 'No WireGuard server public key saved — enter it in the config form.',
  'api.wgClientKeyMissing': 'The client private key is missing — rebuild the config.',
  'api.sniRequired': 'TLS or REALITY needs an SNI or domain.',
  'api.protocolNoLink': '{protocol} has no shareable link.',
  'api.tunnelTypeNotImplemented': 'The "{type}" type is not implemented yet; only reverse SSH tunnels work for now.',
  'api.tunnelPortsRequired': 'A tunnel needs both a local and a remote port.',
  'api.tunnelAlreadyRunning': 'This tunnel is already running.',
  'api.idInvalid': 'Invalid id in the request.',
  'api.invalidRequest': 'Invalid request (id or value).',
  'api.internal': 'Internal server error — try once more.',
  'api.methodNotAllowed': 'That method is not supported.',
  'api.configNotFound': 'Config not found.',
  'api.serverNotFound': 'Server not found.',
  'api.tunnelNotFound': 'Tunnel not found.',
  'api.userNotFound': 'User not found.',
  'api.userExists': 'That username is already taken.',
  'api.cannotDeleteSelf': 'You cannot delete your own account.',
  'api.serverHasDependents': 'This server still has {configs} config(s) and {tunnels} tunnel(s) — delete those first.',
  'api.deployFailed': 'Deploying the proxy on the server failed.',
  'api.unauthorized': 'Session expired — sign in again.',
  'api.forbidden': 'You do not have access to this part.',
""",
'ru': """
  // ── Коды ошибок API (см. src/lib/validate.ts)
  'api.badCredentials': 'Неверное имя пользователя или пароль.',
  'api.rateLimited': 'Слишком много неудачных попыток — попробуйте через {sec} секунд.',
  'api.currentPasswordWrong': 'Текущий пароль неверный.',
  'api.passwordTooShort': 'Пароль должен быть не короче 8 символов.',
  'api.usernamePasswordRequired': 'Нужны имя пользователя и пароль.',
  'api.nameHostRequired': 'Нужны имя сервера и хост.',
  'api.authTypeInvalid': 'Способ входа должен быть «пароль» или «ключ».',
  'api.portRange': 'Порт должен быть числом от 1 до 65535.',
  'api.tunnelPortsRange': 'Локальный и внешний порты должны быть числами от 1 до 65535.',
  'api.configFieldsRequired': 'Нужны имя, сервер и порт.',
  'api.protocolInvalid': 'Такой протокол не поддерживается.',
  'api.socksOnly': 'Это работает только для конфига SOCKS5.',
  'api.proxyNotDeployed': 'Прокси ещё не запущен на сервере — сначала нажмите «Развернуть на сервере».',
  'api.wgPubKeyMissing': 'Публичный ключ сервера (PubKey) для WireGuard не сохранён — впишите его в форму.',
  'api.wgClientKeyMissing': 'Приватный ключ клиента отсутствует — пересоздайте конфиг.',
  'api.sniRequired': 'Для TLS или REALITY нужен SNI или домен.',
  'api.protocolNoLink': 'Для протокола {protocol} ссылка не формируется.',
  'api.tunnelTypeNotImplemented': 'Тип «{type}» ещё не реализован; сейчас работают только обратные SSH-туннели.',
  'api.tunnelPortsRequired': 'Туннелю нужны и локальный, и внешний порт.',
  'api.tunnelAlreadyRunning': 'Этот туннель уже запущен.',
  'api.idInvalid': 'Некорректный идентификатор в запросе.',
  'api.invalidRequest': 'Некорректный запрос (идентификатор или значение).',
  'api.internal': 'Внутренняя ошибка сервера — попробуйте ещё раз.',
  'api.methodNotAllowed': 'Этот метод не поддерживается.',
  'api.configNotFound': 'Конфиг не найден.',
  'api.serverNotFound': 'Сервер не найден.',
  'api.tunnelNotFound': 'Туннель не найден.',
  'api.userNotFound': 'Пользователь не найден.',
  'api.userExists': 'Такое имя пользователя уже занято.',
  'api.cannotDeleteSelf': 'Свою учётную запись удалить нельзя.',
  'api.serverHasDependents': 'На этом сервере ещё {configs} конфиг(ов) и {tunnels} туннел(ей) — сначала удалите их.',
  'api.deployFailed': 'Развернуть прокси на сервере не удалось.',
  'api.unauthorized': 'Сессия истекла — войдите заново.',
  'api.forbidden': 'У вас нет доступа к этому разделу.',
""",
'ar': """
  // ── رموز أخطاء الـ API (انظر src/lib/validate.ts)
  'api.badCredentials': 'اسم المستخدم أو كلمة المرور غير صحيحة.',
  'api.rateLimited': 'محاولات فاشلة كثيرة — أعد المحاولة بعد {sec} ثانية.',
  'api.currentPasswordWrong': 'كلمة المرور الحالية غير صحيحة.',
  'api.passwordTooShort': 'كلمة المرور يجب ألا تقل عن ٨ أحرف.',
  'api.usernamePasswordRequired': 'اسم المستخدم وكلمة المرور مطلوبان.',
  'api.nameHostRequired': 'اسم الخادم والعنوان مطلوبان.',
  'api.authTypeInvalid': 'طريقة التحقق يجب أن تكون «كلمة مرور» أو «مفتاح».',
  'api.portRange': 'المنفذ يجب أن يكون رقماً بين ١ و٦٥٥٣٥.',
  'api.tunnelPortsRange': 'المنفذ المحلي والخارجي يجب أن يكونا رقمين بين ١ و٦٥٥٣٥.',
  'api.configFieldsRequired': 'الاسم والخادم والمنفذ مطلوبة.',
  'api.protocolInvalid': 'هذا البروتوكول غير مدعوم.',
  'api.socksOnly': 'هذا يعمل فقط على ملف SOCKS5.',
  'api.proxyNotDeployed': 'البروكسي لم يعمل على الخادم بعد — اضغط «النشر على الخادم» أولاً.',
  'api.wgPubKeyMissing': 'لم يُحفظ المفتاح العام لخادم WireGuard — أدخله في النموذج.',
  'api.wgClientKeyMissing': 'المفتاح الخاص بالعميل مفقود — أعد إنشاء الملف.',
  'api.sniRequired': 'يحتاج TLS أو REALITY إلى SNI أو نطاق.',
  'api.protocolNoLink': 'البروتوكول {protocol} لا يُنتج رابطاً قابلاً للاستخدام.',
  'api.tunnelTypeNotImplemented': 'النوع «{type}» لم يُنفَّذ بعد؛ حالياً يعمل النفق العكسي SSH فقط.',
  'api.tunnelPortsRequired': 'النفق يحتاج منفذاً محلياً ومنفذاً خارجياً.',
  'api.tunnelAlreadyRunning': 'هذا النفق يعمل بالفعل.',
  'api.idInvalid': 'المعرّف في الطلب غير صالح.',
  'api.invalidRequest': 'طلب غير صالح (المعرّف أو القيمة).',
  'api.internal': 'خطأ داخلي في الخادم — جرّب مرة أخرى.',
  'api.methodNotAllowed': 'هذه الطريقة غير مدعومة.',
  'api.configNotFound': 'لم يُعثر على الملف.',
  'api.serverNotFound': 'لم يُعثر على الخادم.',
  'api.tunnelNotFound': 'لم يُعثر على النفق.',
  'api.userNotFound': 'لم يُعثر على المستخدم.',
  'api.userExists': 'اسم المستخدم هذا مستخدم بالفعل.',
  'api.cannotDeleteSelf': 'لا يمكنك حذف حسابك.',
  'api.serverHasDependents': 'على هذا الخادم {configs} ملف و{tunnels} نفق؛ احذفها أولاً.',
  'api.deployFailed': 'فشل نشر البروكسي على الخادم.',
  'api.unauthorized': 'انتهت الجلسة — سجّل الدخول من جديد.',
  'api.forbidden': 'لا تملك صلاحية الوصول إلى هذا القسم.',
""",
'zh': """
  // ── API 错误码（见 src/lib/validate.ts）
  'api.badCredentials': '用户名或密码错误。',
  'api.rateLimited': '失败次数过多 — 请在 {sec} 秒后重试。',
  'api.currentPasswordWrong': '当前密码错误。',
  'api.passwordTooShort': '密码至少需要 8 个字符。',
  'api.usernamePasswordRequired': '用户名和密码为必填项。',
  'api.nameHostRequired': '服务器名称和地址为必填项。',
  'api.authTypeInvalid': '认证方式必须为密码或密钥。',
  'api.portRange': '端口必须是 1 到 65535 之间的数字。',
  'api.tunnelPortsRange': '本地端口与远端端口必须是 1 到 65535 之间的数字。',
  'api.configFieldsRequired': '名称、服务器和端口为必填项。',
  'api.protocolInvalid': '不支持该协议。',
  'api.socksOnly': '该操作仅适用于 SOCKS5 配置。',
  'api.proxyNotDeployed': '代理尚未在服务器上运行 — 请先点击「部署到服务器」。',
  'api.wgPubKeyMissing': '尚未填写 WireGuard 服务器公钥 — 请在配置表单中填写。',
  'api.wgClientKeyMissing': '缺少客户端私钥 — 请重新生成配置。',
  'api.sniRequired': 'TLS 或 REALITY 需要 SNI 或域名。',
  'api.protocolNoLink': '{protocol} 无法生成可用的分享链接。',
  'api.tunnelTypeNotImplemented': '类型「{type}」尚未实现；目前仅支持 SSH 反向隧道。',
  'api.tunnelPortsRequired': '隧道需要本地端口和远端端口。',
  'api.tunnelAlreadyRunning': '该隧道已在运行。',
  'api.idInvalid': '请求中的 id 无效。',
  'api.invalidRequest': '请求无效（id 或参数）。',
  'api.internal': '服务器内部错误 — 请再试一次。',
  'api.methodNotAllowed': '不支持该方法。',
  'api.configNotFound': '未找到配置。',
  'api.serverNotFound': '未找到服务器。',
  'api.tunnelNotFound': '未找到隧道。',
  'api.userNotFound': '未找到用户。',
  'api.userExists': '该用户名已被占用。',
  'api.cannotDeleteSelf': '无法删除自己的账号。',
  'api.serverHasDependents': '该服务器还有 {configs} 个配置和 {tunnels} 条隧道，请先删除它们。',
  'api.deployFailed': '在服务器上部署代理失败。',
  'api.unauthorized': '会话已过期 — 请重新登录。',
  'api.forbidden': '你没有访问该部分的权限。',
""",
}

for lang, block in BLOCKS.items():
    path = f'src/i18n/{lang}.ts'
    src = io.open(path, encoding='utf-8').read()
    if "'api.badCredentials'" in src:
        print(f'{lang}: قبلاً اضافه شده — رد شد')
        continue
    anchor = '} as const;' if lang == 'fa' else '};'
    idx = src.rindex('\n' + anchor)
    src = src[:idx] + '\n' + block + anchor.lstrip('\n') if False else src[:idx] + block + anchor + src[idx + 1 + len(anchor):]
    io.open(path, 'w', encoding='utf-8').write(src)
    print(f'{lang}: {block.count(chr(10)) - 1} کلید خطا اضافه شد')
